version: "3"

networks:
  db:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - postgres
    environment:
      CONFIG_PATH: "--config=./config/production/config.toml"
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - db

  postgres:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: histories
    volumes:
      - ./config/production/db-setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - db